version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --only=dev
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Cleaning build dependencies
      - npm prune --production
    finally:
      - export BUCKET=codepipeline-us-east-2-106888872198
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml

artifacts:
  files:
    - "index.js"
    - "template.yml"
    - "outputtemplate.yml"
    - "dist/**/*.js"
    - "node_modules/**/*"
