version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --only=dev
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Cleaning build dependencies
      - npm prune --production
    finally:
      - sed -i "s/CODEBUILD_BUILD_ID/$CODEBUILD_BUILD_ID/g" template.yml

artifacts:
  type: zip
  files:
    - "index.js"
    - "template.yml"
    - "outputtemplate.yml"
    - "dist/**/*.js"
    - "node_modules/**/*"
