AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: IAmNater GraphQL API
  
Globals:
  Function:
    Timeout: 3

Resources:
  IAmNaterGraphQL:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: s3://codepipeline-us-east-2-106888872198/iamnater_com-api/BuildArtif/CODEBUILD_BUILD_ID
      Events:
        GraphQlRequest:
          Type: Api
          Properties:
            Path: /graphql
            Method: post

